### PR TITLE
add autoupdating

### PR DESCRIPTION
**Pull request by webmsgr**
pls remove github-api branch

### CODE REVIEW

**Comment by webmsgr** [comment]
prettier got its hands on the index.tsx file lmafo

**Comment by webmsgr** [comment]
call `fupdate()` in console and see if its only firefox in private mode that freaks out about this.

**Comment by webmsgr** [comment]
idk if the new commit works on all browsers, can ya test it @insberr? just run `fupdate()` in the console

**Comment by insberr** [comment]
Yeah if cloud flares will loading

**Comment by webmsgr** [comment]
Does it not work on the iPads? Or did I break something.

**Comment by insberr** [comment]
Works in chrome on my iphone so I assume it would work on the iPads too.

**Comment by webmsgr** [comment]
not tested lmafo

**Comment by insberr** [comment]
ill test it and then do you want me to review and merge?

**Comment by insberr** [comment]
errors errors errors
image

**Comment by insberr** [comment]
Schedule renders but then dissappears shortly after it tries to update. Upon looking at the error, it is this according to react
image

**Comment by insberr** [comment]
can you just update root without unmounting or something idk lol

**Comment by webmsgr** [comment]
ready to merge

**Comment by webmsgr** [comment]
It's been doing this check for about an hour now

**Comment by webmsgr** [comment]
todo fixes: 
- add feature to only try reloading 3 times
- make autoupdating do a cool thing called not fading in
- give up a first born to the code gods
- add a toast to the thing so that it says "hey boyo schedule personalizer was just updated!!!!1!!!"

**Comment by insberr** [comment]
ready to go cause its snowing

**Review by insberr — APPROVED** [review]
lets go aside from some slight features

**Pull request merged**
