### PR TITLE
V10 scs astary svelte

### PR DESCRIPTION
**Pull request by webmsgr**
Svelte maybe

### CODE REVIEW

**Comment by webmsgr** [comment]
Lemme fix gh actions so that this branch is built

**Comment by webmsgr** [comment]
Actually why isn't this building

**Comment by webmsgr** [comment]
Finally

**Comment by webmsgr** [comment]
Svelte actually has a tutorial https://svelte.dev/tutorial/basics

**Comment by webmsgr** [comment]
I still have to make the bottom bar better bc flowbite doesn't have a bottom app bar.

fine, I'll do it myself

**Comment by webmsgr** [comment]
current commit is horribly broken

**Comment by webmsgr** [comment]
@insberr im thinking of merging this to `v10-scs-astary` and somehow renaming that branch to just `v10` (Can you even rename git branches?)

**Comment by webmsgr** [comment]
You can!

**Comment by webmsgr** [comment]
@insberr review and prepare to merge and rename v10 branch

**Review by insberr — APPROVED** [review]
Looks fine

**Pull request merged**
