### PR TITLE
React Router

### PR DESCRIPTION
**Pull request by webmsgr**
replaces the old page system with react router

Known bugs:
* ~Manual navigation to /setup errors when already setup~ Fixed in 602dda4
* ~Manual dev term input doesn't work (I screwed up)~ Fixed in 8e27c31523f25f403400a522eb000a1f4b8aebc5

### CODE REVIEW

**Comment by webmsgr** [comment]
Think I figured out the issue, forgor react.suspense

**Comment by webmsgr** [comment]
Does cloudflare route all unknown routes to index.html, there's a hack way to fix it if it doesn't but still.

**Comment by webmsgr** [comment]
TODO: setup caching with the service worker.

**Comment by webmsgr** [comment]
TODO: editor page integrate with react router

**Review by insberr — APPROVED** [review]
looks good

**Pull request merged**
