### PR TITLE
Licenses and stuff

### PR DESCRIPTION
**Pull request by webmsgr**
Might be a good idea to embed license info in a special page. 

Parcel can import .mdx files: (https://parceljs.org/languages/mdx/)

### CODE REVIEW

**Comment by webmsgr** [comment]
Yay or Nay?

**Comment by webmsgr** [comment]
Maybe use https://github.com/TobyAndToby/generate-license-file Instead of the plug-in?

**Comment by insberr** [comment]
Dropdown pre element with license in the credits page?

**Comment by webmsgr** [comment]
Should I make it a drop down?

**Comment by insberr** [comment]
probably, so it looks better? and i mean a collapse like we do on the schedule for more class details

**Comment by webmsgr** [comment]
Ok

**Comment by webmsgr** [comment]
Ok

**Comment by webmsgr** [comment]
Might be a good idea to move some deps to dev deps

**Comment by webmsgr** [comment]
@insberr ready to review

**Review by insberr — APPROVED** [review]
looks good

**Pull request merged**
