### PR TITLE
V10

### PR DESCRIPTION
**Pull request by webmsgr**
DO NOT CONTINUE UNTIL SCS IS DONE
DO NOT TOUCH UNTIL SCS IS DONE
DO NOT THINK ABOUT IT UNTIL SCS IS DONE

***DO*** 

***NOT***

### CODE REVIEW

**Comment by webmsgr** [comment]
i based this off another pr like an idiot lmafo it should be fine

**Comment by insberr** [comment]
> i based this off another pr like an idiot lmafo it should be fine

can i copy these files into a new branch/pr based on master? so we dont mess a whole bunch of stuff up.

**Comment by webmsgr** [comment]
It shouldn't mess anything up. Just some extra commits that don't matter bc the files are removed in 96607a71424d44c0f9a7186e5893d5770e188c45. We are still merging into master

**Comment by webmsgr** [comment]
Also consider the 3rd line:
> DO NOT THINK ABOUT IT UNTIL SCS IS DONE

**Comment by insberr** [comment]
I don't want to deal with merge conflicts

**Pull request closed without merging**
