### PR TITLE
V10 scs astary

### PR DESCRIPTION
**Pull request by insberr**
DO NOT TOUCH OR ELSE.
DO NOT TOUCH UNTILL SCS
DO NOT TOUCH UNTILL ASTARY
DO NOT
TOUCH
PR

Complete rewrite, again.

### CODE REVIEW

**Comment by webmsgr** [comment]
Cloudflare broke. Joy

**Comment by webmsgr** [comment]
And it's fixed

**Comment by insberr** [comment]
merge conflicts galore lol

**Comment by webmsgr** [comment]
Part of the job unfortunately
How it feels sometimes
B94DE19F-1717-463B-8B5B-001621B52DAB

**Pull request closed without merging**
