### PR TITLE
Jake

### PR DESCRIPTION
**Pull request by webmsgr**
Looked pretty cool, probably need to add actual descriptions + don't just use exec();

### CODE REVIEW

**Comment by webmsgr** [comment]
Other things:
- this pr will decouple legal.mdx and the splash screens from the repo (.gitignored) eventually
- Cloudflare will need to be updated to point to 'yarn cloudflare'

**Comment by webmsgr** [comment]
Please check everything I've moved to Jake

**Review by insberr — APPROVED** [review]
looks good

**Comment by webmsgr** [comment]
todo: move the splashscreens to a new file, splash.html, then use magic to include it

**Review by insberr — APPROVED** [review]
h

**Comment by insberr** [comment]
> todo: move the splashscreens to a new file, splash.html, then use magic to include it

pain-glhf

**Comment by webmsgr** [comment]
thanks parcel api

**Comment by webmsgr** [comment]
looks good, hope this wont break shit!

**Pull request merged**
